"""
generator.py
------------
Converts raw agent outputs into a structured Markdown Judgement Report.
"""

import re
from datetime import datetime


def _extract(pattern: str, text: str, default: str = "N/A") -> str:
    """Extract first regex group from text, with a default fallback."""
    match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
    return match.group(1).strip() if match else default


def _extract_consistency_score(text: str) -> int:
    match = re.search(r"OVERALL CONSISTENCY SCORE[:\s]+(\d{1,3})", text, re.IGNORECASE)
    if match:
        return min(int(match.group(1)), 100)
    match = re.search(r"\b(\d{1,3})\b", text)
    return int(match.group(1)) if match else 70


def _extract_fabrication_prob(text: str) -> str:
    match = re.search(r"FABRICATION PROBABILITY[:\s]+([\d]+%?)", text, re.IGNORECASE)
    return match.group(1) if match else "N/A"


def _extract_risk_level(text: str) -> str:
    match = re.search(r"RISK LEVEL[:\s]+(Low|Medium|High|Critical)", text, re.IGNORECASE)
    return match.group(1) if match else "N/A"


def _extract_recommendation(text: str) -> str:
    match = re.search(r"RECOMMENDATION[:\s]+(PASS|FAIL.*?)(?:\n|$)", text, re.IGNORECASE)
    return match.group(1).strip() if match else "N/A"


def generate_report(
    title: str,
    arxiv_url: str,
    sections: dict,
    agent_results: dict,
) -> str:
    """
    Build and return the full Judgement Report as a Markdown string.

    Args:
        title:         Paper title (from scraper).
        arxiv_url:     Original arXiv URL.
        sections:      Parsed sections dict.
        agent_results: Output dict from crew_setup.run_agents().

    Returns:
        Markdown string of the complete report.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    consistency_raw  = agent_results.get("consistency", "")
    grammar_raw      = agent_results.get("grammar", "")
    novelty_raw      = agent_results.get("novelty", "")
    fact_check_raw   = agent_results.get("fact_check", "")
    fabrication_raw  = agent_results.get("fabrication", "")

    # ── Extract key metrics ────────────────────────────────────────────────
    consistency_score = _extract_consistency_score(consistency_raw)
    grammar_rating    = _extract("GRAMMAR RATING[:\s]+(High|Medium|Low)", grammar_raw, "Medium")
    novelty_index     = _extract(
        r"NOVELTY INDEX[:\s]+(Highly Novel|Moderately Novel|Incremental|Low Novelty)",
        novelty_raw, "Moderately Novel"
    )
    fabrication_prob  = _extract_fabrication_prob(fabrication_raw)
    risk_level        = _extract_risk_level(fabrication_raw)
    recommendation    = _extract_recommendation(fabrication_raw)
    exec_summary      = _extract(r"EXECUTIVE SUMMARY[:\s]+(.*?)(?:\n\n|\d+\.)", fabrication_raw,
                                 "See detailed analysis below.")

    # ── Colour-code recommendation ─────────────────────────────────────────
    rec_emoji = "✅" if "PASS" in recommendation.upper() else "❌"

    report = f"""# 📄 Agentic Research Paper Judgement Report

**Generated:** {now}  
**Paper Title:** {title or "Unknown"}  
**arXiv URL:** {arxiv_url}

---

## 🏆 Executive Summary

> {exec_summary}

### {rec_emoji} Recommendation: `{recommendation}`

---

## 📊 Score Dashboard

| Metric | Score / Rating |
|--------|---------------|
| Consistency Score | **{consistency_score} / 100** |
| Grammar Rating | **{grammar_rating}** |
| Novelty Index | **{novelty_index}** |
| Fabrication Probability | **{fabrication_prob}** |
| Risk Level | **{risk_level}** |

---

## 🧠 1. Consistency Analysis

{consistency_raw}

---

## ✍️ 2. Grammar & Language Analysis

{grammar_raw}

---

## 🧪 3. Novelty Assessment

{novelty_raw}

---

## 🔍 4. Fact-Check Log

{fact_check_raw}

---

## ⚠️ 5. Fabrication Risk Assessment

{fabrication_raw}

---

## 📝 Paper Sections Summary

| Section | Length (chars) |
|---------|---------------|
| Abstract | {len(sections.get('abstract', ''))} |
| Introduction | {len(sections.get('introduction', ''))} |
| Methodology | {len(sections.get('methodology', ''))} |
| Results | {len(sections.get('results', ''))} |
| Conclusion | {len(sections.get('conclusion', ''))} |

---

*Report generated by the Agentic Research Paper Evaluator — powered by CrewAI + Gemini.*
"""
    return report


def save_report(report_md: str, output_path: str = "judgement_report.md") -> str:
    """Save the Markdown report to disk and return the path."""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report_md)
    print(f"[Report] ✅ Report saved to: {output_path}")
    return output_path
